In [5]:
import numpy as np 
a = np.array([1,2,34])
a

array([ 1,  2, 34])

In [6]:
print(a)

[ 1  2 34]


In [7]:
print(a.shape)

(3,)


In [8]:
print(a.shape[0])

3


In [9]:
b= np.array([[1,2,34],[2,45,87]])
b

array([[ 1,  2, 34],
       [ 2, 45, 87]])

In [10]:
print(b)

[[ 1  2 34]
 [ 2 45 87]]


In [11]:
print(b.shape)

(2, 3)


In [12]:
print(b.shape[0])

2


In [13]:
print(b.shape[1])

3
